[ALPS02875518] blocktag: fix build fail when MODULES is enable
When CONFIG_MODULES is enabled, blocktag.c build fail with:
drivers/misc/mediatek/blocktag/blocktag.c:229:1: error: expected , or ; before static

Add the missing ;

Change-Id: Ia82c2eec6cdb50b7d8f6fe07497d4d7fd76d4f1a
CR-Id: ALPS02875518
Feature: others
MTK-Commit-Id: 4f4eaeeb55591d5373d05958ad96675b3bc75acc