[ALPS02792903] revert "PTPOD: mt8167: add ptp aee-info"
This reverts commit eeff59b2eb7a5354877dfe8ca16882c729698481.

[Detail]
The following projects cannot be built successfully
because of above commit id. Therefore, I revert that patch.

1. tb8167p3_bsp-eng

drivers/built-in.o: In function `ptp_set_ptp_volt':
/alps/DailyBuild/CodeBase/alps/kernel-4.4/drivers/misc/
mediatek/base/power/mt8167/
mtk_ptp.c:1734: undefined reference to `__aeabi_uldivmod'

make[1]: *** [vmlinux] Error 1
make[1]: Leaving directory `/alps/DailyBuild/CodeBase/alps/
out/target/product/tb8167p3_bsp/obj/KERNEL_OBJ'
make: *** [sub-make] Error 2

Change-Id: I679bf74119da34877fba5d927e989b6b5ce5e890
Feature: PTP-OD (Performance Thermal Power-Over Drive)
CR-Id: ALPS02792903
Signed-off-by: Roger Lu <roger.lu@mediatek.com>